

stages:
  - test
  - docu

run_tests:
  image: python:3.8-slim
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

build_docu:
  image: python:3.8-slim
  stage: docu
  script:
    - pip install -r doc_requirements.txt
    - mkdocs build
  artifacts:
    paths:
      - site
