

stages:
  - test
  - docu
  - deploy

run_tests_3.8:
  image: python:3.8-bullseye
  stage: test
  script:
    - pip install --upgrade pip
    - pip install -r requirements/test_requirements.txt
    - pip install .
    - coverage run -m pytest tests/ --html=test_report/report.html --junitxml=report.xml
    - coverage report
    - coverage xml
    - coverage html
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov
      - test_report


## No need for python3.6 support
# run_tests_3.6:
#   image: python:3.6-bullseye
#   stage: test
#   script:
#     - pip install .
#     - python -m unittest discover -s tests


build_docu:
  image: python:3.8-bullseye
  stage: docu
  script:
    - pip install --upgrade pip
    - pip install -r requirements/doc_requirements.txt
    - pip install .
    - mkdocs build
  artifacts:
    paths:
      - site

upload_docu:
  image: debian:latest
  stage: deploy
  script:
    - echo "Uploading docu"
    - rm -rf /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/latest
    - rm -rf /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_TAG
    - mkdir -p /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_TAG
    - mkdir -p /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/latest
    - cp -R site/* /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_TAG
    - cp -R site/* /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/latest
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'


# This is not so easy because the badge cannot be linked to a commit dependend link - So I could maybe link to the latest on develop but thats not good. 
# upload_reports:
#   image: debian:latest
#   stage: deploy
#   script:
#     - echo "Uploading reports"
#     - mkdir -p /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/reports/CI_COMMIT_SHA
#     - cp -R htmlcov/* /home/www/htdocs/apis/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_TAG
