

stages:
  - test
  - docu

run_tests_3.8:
  image: python:3.8-slim
  stage: test
  script:
    - pip install .
    - python -m unittest discover -s tests

run_tests_3.6:
  image: python:3.6-slim
  stage: test
  script:
    - pip install .
    - python -m unittest discover -s tests

build_docu:
  image: python:3.8-slim
  stage: docu
  script:
    - pip install -r doc_requirements.txt
    - pip install .
    - mkdocs build
  artifacts:
    paths:
      - site
