site_name: CoBaIR - Documentation
plugins:
  - include-markdown
  - search
  - mkdocstrings

theme:
  name: 'material'
  palette:
    primary: orange
    accent: indigo

markdown_extensions:
  - admonition

nav:
  - Getting started: index.md
  - API Documentation: API.md