site_name: CoBaBIR - Documentation
plugins:
  - include-markdown
  - search
  - mkdocstrings

theme:
  name: 'material'
  palette:
    primary: orange
    accent: indigo

nav:
  - Getting started: index.md
  - API Documentation: API.md